### ISSUE TITLE
Two spaces are wider than two letters

### ISSUE THREAD

**Issue by johnmapeson** [satsuyako/YomogiFont#12]
Amazing font, but there is an issue that really makes me sad.

Here is a test (Yomogi v3.100, 24 points):

<img width="116" alt="image" src="https://github.com/satsuyako/YomogiFont/assets/129062294/4f19b8b8-eedd-4718-81f8-b191d44f6ad7">

As you can see, two spaces (line 2) are wider than two letters (line 1), and so it is not possible to use Yomogi, for example, for code currently.

And here is how I expected it to be:

<img width="75" alt="image" src="https://github.com/satsuyako/YomogiFont/assets/129062294/033be832-bce2-4c03-a2d5-b8ec2224efc0">

**Comment by satsuyako** [comment]
Thank you for pointing that out!
I set the width of the half-width space to the same width as the letters of the alphabet.
<img width="622" alt="スクリーンショット 2023-05-22 19 35 57" src="https://github.com/satsuyako/YomogiFont/assets/54973107/6175832e-2a9f-4893-9c98-c5b67f53f945">
