### ISSUE TITLE
Colons and semicolons

### ISSUE THREAD

**Issue by johnmapeson** [satsuyako/YomogiFont#13]
I don't know whether this is by design or not, but vertical alignment of `:` and `;` is somewhat unusual, it is too high.

<img width="274" alt="image" src="https://github.com/satsuyako/YomogiFont/assets/129062294/8625de44-844d-49cd-922c-76ad7bcea8cf">

They are typically located on the same height as lowercase letters, so here is how I expected them to be:

<img width="222" alt="image" src="https://github.com/satsuyako/YomogiFont/assets/129062294/b424618c-9648-49f1-96f2-8d2712ed3b72">

**Comment by satsuyako** [comment]
Thank you for letting me know:)
I adjusted the height of ":" and ";" to the same height as lowercase letters.
<img width="818" alt="スクリーンショット 2023-05-22 19 39 26" src="https://github.com/satsuyako/YomogiFont/assets/54973107/31d320b6-cbf3-4a14-8a8f-a67faee96424">
