### ISSUE TITLE
U+0027 should be straight

### ISSUE THREAD

**Issue by johnmapeson** [satsuyako/YomogiFont#14]
There is one another issue with punctuation.

Currently, U+0027 `'` looks as

<img width="307" alt="image" src="https://github.com/satsuyako/YomogiFont/assets/129062294/7373d71e-4cbf-47d3-b81f-4b3d2db5a590">

Unfortunately, this is wrong.

U+0027 is simply a "sister" of U+0022 `"`, and it should be straight:

<img width="391" alt="image" src="https://github.com/satsuyako/YomogiFont/assets/129062294/32212960-435f-4053-8424-c2eb08a76cd4">

U+0027 characters are used, for instance, for inner quotations:

<img width="482" alt="image" src="https://github.com/satsuyako/YomogiFont/assets/129062294/d73dad14-6bb9-42aa-be3f-4a41807d1e4c">

The shape which is currently used for U+0027 should be used for U+2019 instead. Here they are, all together:

<img width="402" alt="image" src="https://github.com/satsuyako/YomogiFont/assets/129062294/53d03b12-7a2c-4b04-8a5d-b383e5aa3788">

**Comment by satsuyako** [comment]
Thank you  for your kind instruction!
I changed U+0027 ' to a straight shape like U+0022.

<img width="831" alt="スクリーンショット 2023-05-29 8 20 44" src="https://github.com/satsuyako/YomogiFont/assets/54973107/ef52c4a0-8e2f-4f1a-9afe-ce1539633ca4">

Please let me know if there is anything else.

**Comment by johnmapeson** [comment]
... And to make it even better, U+0022 and U+0027 should be closer to the center of their boxes:

<img width="297" alt="image" src="https://github.com/satsuyako/YomogiFont/assets/129062294/2d729908-a184-477e-ba5e-7987080b4308">

Thank you for quick responses `:)`

**Comment by satsuyako** [comment]
U+0022 and U+0027 have been moved to the middle position of these boxes:
<img width="461" alt="スクリーンショット 2023-05-29 16 53 11" src="https://github.com/satsuyako/YomogiFont/assets/54973107/8225e39e-0060-4529-b702-b64635f4bfb0">
<img width="461" alt="スクリーンショット 2023-05-29 16 52 18" src="https://github.com/satsuyako/YomogiFont/assets/54973107/e4d4ca03-30d3-4a60-a1b5-c820c15d98fc">
