### ISSUE TITLE
The width of tilde, the heigh of equals sign

### ISSUE THREAD

**Issue by johnmapeson** [satsuyako/YomogiFont#15]
What I think is also can be improved is the height of `=` (equals sign, U+003D) and the width of `~` (tilde, U+007E).

The lines in `=` are too far away one from another, I think the top line can be moved a bit lower:

<img width="341" alt="image" src="https://github.com/satsuyako/YomogiFont/assets/129062294/794b99c0-ddb6-4c36-8cac-a1d2377f6a53">

`~` should be the same width as `-` (U+002D) and `=`, whereas currently it is much shorter.

<img width="101" alt="image" src="https://github.com/satsuyako/YomogiFont/assets/129062294/e39928e1-d003-4dfa-a85b-cf9b1367df20">

**Comment by satsuyako** [comment]
I moved the top line of `=` (U+003D) down a bit and adjusted `~` (U+007E) to be the same width as `-` (U+002D):
<img width="591" alt="スクリーンショット 2023-05-29 20 09 48" src="https://github.com/satsuyako/YomogiFont/assets/54973107/866d4154-4c51-46d4-9abd-3480487bf0ad">
