### ISSUE TITLE
Comma and comma-part of semicolon are too large.

### ISSUE THREAD

**Issue by johnmapeson** [satsuyako/YomogiFont#16]
I hope you haven't tired of my posts here 😄 

This seems to be the final thing that would be great to improve. Maybe it's just for my eyes, but `,` (comma, U+002C) and the comma-part of of `;` look larger than `.` (period, U+002E).

><img width="221" alt="image" src="https://github.com/satsuyako/YomogiFont/assets/129062294/a4e8d371-3b51-428e-8026-87c9abe7c1f7">

><img width="277" alt="image" src="https://github.com/satsuyako/YomogiFont/assets/129062294/f91a1a76-5a84-4f70-8fe3-8d846f95995e">

If you agree, than I suppose it would be better to reduce their size a little.

**Comment by johnmapeson** [comment]
By the way, which app you use to draw fonts? I want to draw a font of my own script.

**Comment by satsuyako** [comment]
The commas is certainly big! I fixed these as well:)

The font "Yomogi" is the first font I made more than 10 years ago, so I handwritten hiragana, alphanumeric characters, and a few kanji with an iFontMaker app on the ipad, and the rest of the kanjis with Illustrator. I pasted it into Glyphs.

When I create a script font like the one below, I draw lines with the pen tool in Illustrator, convert it to outlines, paste it into Glyphs, and then adjust the details.
<img width="854" alt="スクリーンショット 2023-05-30 6 56 52" src="https://github.com/satsuyako/YomogiFont/assets/54973107/5837a5a6-ee86-4b69-87db-f917b9533563">

If you want to draw a font that looks more like handwriting, I recommend scanning your handwriting on paper, extracting the outlines with an app like Potrace, and adjusting with Glyphs.(If not, you may be able to make it using Glyphs only.)

**Comment by johnmapeson** [comment]
Thank you so much. I will try the next weekend :)
