### ISSUE TITLE
Font does not contain full JIS1 / JIS2  or Google Latin Core coverage

### ISSUE THREAD

**Issue by aaronbell** [satsuyako/YomogiFont#2]
These JIS1 / JIS2 glyphs appear to be missing from the font:

倦僅儲兎冤勒卿厩叉叛叟咬哨喰嘲噂噌囀堵娩屑屠巷庖廟廻徘徽恢愈戝扁扈挺挽捗捲揃摯摺撰擢斧晦杓杖梗楢楯榊榔槌樋樽櫛歎汲淫溢溺漣濶瀕瀞瀦灘灸灼煉煎煽爺牌牙狡猷瑤甑甕甦疼皷瞥祁祇禰秤稗穿竈竟笈筵箭箸篇篝簾籾粂翫翰腱腿艘芒芦茨葛蓬蔑蔽薩薯藷虔蛸蜃蝕蠅袂袍袒袗袙袢袤袮袰袱袿裃裄裔裘裙裨裲裴裹裼褂褄褊褌褓褝褞褥褪褫褶褸褻襁襃襄襌襍襖襞襠襤襦襪襭襯襴襷襾覃覈覊覓覘覡覦覩覬覯覲覺覿觀觚觜觝觧觴觸訊訌訐訖訛訝訥訶註詁詆詈詒詛詬詭詮詼誂誄誅誑誚誡誣誥誦誨誹諂諍諚諛諞諠諡諢諤諱諳諷諺謇謌謎謐謔謖謗謚謦謨謫謬謳謾譁證譌譎譏譖譚譛譟譫譬譯譴譽讀讌讎讒讖讙讚谺谿豁豈豌豎豐豕豢豬豸豹豺豼貂貅貉貊貍貎貔貘貭貮貲貳貶貽賁賈賍賚賤賭賺賻賽贄贅贇贊贍贏贐贓贔贖赧赭赱趁趙趺趾跂跋跌跏跖跚跛跟跣跪跫跼跿踈踉踐踝踞踟踰踴踵蹂蹇蹈蹉蹊蹌蹐蹕蹙蹠蹣蹤蹲蹶蹼躁躄躅躇躊躋躑躓躔躙躡躪躬躰躱躾軅軆軈軋軛軣軫軻軼軾輅輊輌輒輓輕輙輛輜輟輦輳輹輻輾轂轅轆轌轎轗轜轢轣轤辜辟辭辯辷辻辿迂迄迚迢迥迦迯迴迸迹迺逅逋逍逎逑逕逖逗這逡逢逧逵逶逹逼逾遁遉遏遐遑遒遖遘遜遞遡遨遯遲遶遽邀邁邂邉邊邏邨邯邱邵郛郢郤鄂鄒鄙鄭鄰鄲酊酋酖酘酣酥酩酲酳醂醋醢醪醫醯醴醵醺釁釋釐釖釛釜釟釡釵釶釼釿鈑鈔鈕鈞鈩鈬鈿鉅鉈鉉鉋鉐鉗鉚鉞鉤銓銕銖銛銜銷銹鋏鋩鋺錆錏錙錚錢錣錵錺錻鍄鍖鍜鍠鍮鍵鍼鎔鎚鎬鎰鎹鏃鏈鏐鏖鏗鏘鏝鏤鏥鏨鐃鐇鐐鐓鐔鐚鐡鐫鐵鐶鐺鑁鑒鑓鑚鑛鑞鑠鑢鑪鑰鑵鑷鑼鑽鑾鑿钁閂閇閊閔閖閘閙閠閧閨閭閹閻閼閾闃闊闌闍闔闕闖關闡闢闥阡阨阮阯陂陋陌陏陜陝陞陟陦陬陲隍隕隗隘隙隧隨隰隱隲隴隶隸隹雉雋雍雎雕雹霄霆霈霍霎霏霑霓霖霙霤霪霰霹霽霾靂靄靆靈靉靠靡靤靦靨靫靱靹靺靼鞁鞄鞅鞆鞋鞏鞐鞘鞜鞣鞦鞨鞫鞭鞳鞴韃韆韈韋韜韭韲韵韶頏頡頤頷頸頽顆顋顏顫顰顱顳顴颪颱颶飃飄飆飩飫飴餃餅餉餌餐餒餔餘餝餞餠餡餤餬餮餽餾饂饅饉饋饌饐饑饒饕饗馗馘馥馭馮馼駁駑駘駛駝駟駢駭駮駱駲駸駻騁騅騏騙騫騾驀驂驃驅驕驛驟驢驤驥驩驪驫骭骰骼髀髏髑髓體髞髟髢髣髦髫髯髱髴髷髻鬆鬘鬚鬟鬢鬣鬥鬧鬨鬩鬪鬮鬯鬲魃魄魍魎魏魑魘魴鮃鮑鮓鮖鮗鮟鮠鮨鮫鮴鮹鯀鯆鯊鯏鯑鯒鯔鯖鯡鯢鯣鯤鯰鯱鯲鰄鰆鰈鰉鰊鰌鰒鰓鰔鰕鰛鰡鰤鰥鰮鰯鰰鰲鰺鰾鱆鱇鱒鱚鱠鱧鱶鱸鳧鳫鳬鳰鴃鴆鴈鴉鴒鴕鴟鴣鴦鴪鴾鴿鵁鵄鵆鵈鵐鵑鵙鵝鵞鵠鵤鵯鵲鵺鶇鶉鶚鶤鶩鶫鶯鶲鶸鶺鶻鷁鷂鷆鷏鷓鷙鷦鷭鷯鷸鷽鸚鸛鸞鹵鹹鹽麁麈麋麌麑麕麝麥麩麪麭麸黌黏黐黔黜黝點黠黥黨黯黴黶黷黹黻黼黽鼇鼈鼕鼡鼬鼾齎齏齒齔齟齠齡齣齦齧齪齬齲齶齷龕龜龠

Additionally, font is missing the following glyphs from the Google Core Latin set:
00A2 ¢ cent
00A3 £ sterling
00A4 ¤ currency
00A5 ¥ yen
00AC ¬ logicalnot
00B2 ² twosuperior
00B3 ³ threesuperior
00B5 µ micro
00B9 ¹ onesuperior
00BC ¼ onequarter
00BD ½ onehalf
00BE ¾ threequarters
00D2 Ò Ograve
00D3 Ó Oacute
00D4 Ô Ocircumflex
00D5 Õ Otilde
00D6 Ö Odieresis
00D8 Ø Oslash
00D9 Ù Ugrave
00DA Ú Uacute
00DB Û Ucircumflex
00DC Ü Udieresis
00DD Ý Yacute
00DE Þ Thorn
00DF ß germandbls
00F2 ò ograve
00F3 ó oacute
00F4 ô ocircumflex
00F5 õ otilde
00F6 ö odieresis
00F8 ø oslash
00F9 ù ugrave
00FA ú uacute
00FB û ucircumflex
00FC ü udieresis
00FD ý yacute
00FE þ thorn
00FF ÿ ydieresis
2022 • bullet
2044 ⁄ fraction
2074 ⁴ foursuperior
2215 ∕ divisionslash

**Comment by satsuyako** [comment]
Sorry, it seems I updated old data last time.
I fixed the problems.

**Comment by aaronbell** [comment]
Thanks!
