### ISSUE TITLE
Oddities in the Latin design

### ISSUE THREAD

**Issue by aaronbell** [satsuyako/YomogiFont#3]
Exclamation mark quite large / dark compared to Latin letters:
<img width="260" alt="Screen Shot 2020-11-16 at 2 04 33 PM" src="https://user-images.githubusercontent.com/8460297/99313628-ba995500-2814-11eb-94e8-2082014435ce.png">

OE appears to be from another font:
<img width="300" alt="Screen Shot 2020-11-16 at 2 06 16 PM" src="https://user-images.githubusercontent.com/8460297/99313715-e74d6c80-2814-11eb-9bf4-4fe9d8a1acc2.png">

Also observe the sizing of the Scaron and Ydieresis:
<img width="525" alt="Screen Shot 2020-11-16 at 2 07 40 PM" src="https://user-images.githubusercontent.com/8460297/99313874-21b70980-2815-11eb-8ed2-0a5bab55f695.png">
The same kind of issue is present in the lowercase.

Rather inconsistent weighting in the Cyrillic (and Greek as well):
<img width="899" alt="Screen Shot 2020-11-16 at 2 09 12 PM" src="https://user-images.githubusercontent.com/8460297/99314026-54f99880-2815-11eb-84a9-c79178ddab13.png">

**Comment by satsuyako** [comment]
I corrected the some Latin letters. Please check it again.

**Comment by aaronbell** [comment]
Thanks!
