### ISSUE TITLE
Need vendor ID

### ISSUE THREAD

**Issue by aaronbell** [satsuyako/YomogiFont#4]
You do not appear to be [registered with Microsoft](https://docs.microsoft.com/en-us/typography/vendors/). Please [register a vendor ID](https://docs.microsoft.com/en-us/typography/vendors/register).

**Comment by mintoming** [comment]
Vendor ID: STYK

**Comment by satsuyako** [comment]
Thank you for waithing.
I got Vendor ID “STYK” and add it to source file.

**Comment by aaronbell** [comment]
Great. Thanks!
